spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/library_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # http://localhost:8080/swagger-ui.html
  openapi:
    path: /swagger-ui.html

server:
  port: 8080